language: python
python:
    - "2.7"

os:
    - linux

sudo: false

install:
    - bash .travis/install_python.sh
    - export PATH="$HOME/miniconda/bin:$PATH"
    - source activate test-env
    - pip install coveralls

script:
    - nosetests --with-doctest --with-coverage --cover-package=cmt

virtualenv:
    system_site_packages: false

after_success:
    coveralls
