env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"

os:
- linux

sudo: false

install:
- echo "Build on $TRAVIS_OS_NAME"
- if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev";
  fi
- bash .travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- conda info -a
- conda build -q -c csdms conda-recipe
- conda install -q pymt -c csdms --use-local
- pip install coveralls

script:
- nosetests --with-doctest --with-coverage --cover-package=pymt

virtualenv:
    system_site_packages: false

after_success:
- coveralls --verbose
- bash .travis/deploy_to_anaconda.sh
