language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - CHANNEL="dev"
  - secure: N7EenUcspE/pyC1I+TVLowRIBKPylRC6Jlk/DP4u5GAqIkrLqeZPvTjrWBIMvCkZ2B2dPtUZ5IbbxRMTZCTOQxzlcOL4hbJyzsrRJsskya+Mg9oAFYrZJ6D77AZaQ8iwLgGsOBJsTCyBp9iTBiB3x3KZYUwaMPw3SScVrbNOgzk=
  - secure: WAJ1mJAw3aNPUX0PGKAvPnNU+7t2t5dNZv/pTl307UyxZOabSmA88q04VQaq/nwMHCcwO4CDeJY0NxVUURzIWm+K7Hc728MLXUGoM675jUwkQZjjMa2qssRRa5BtWxk790fwdnYjFe7X/3yp2qcOvNzLydYIfSEyZBMLv2iL/64=
sudo: false
jobs:
  include:
  - stage: docs
    script:
    - conda install -q numpydoc sphinx
    - "(cd docs/source && make html)"
    after_success: skip
    os: linux
  - stage: deploy
    env: CHANNEL="main"
    os: linux
    script:
    - conda install -q anaconda-client
    - rsync -r $DROPOFF_URL/pymt/$TRAVIS_BUILD_NUMBER .
    - for f in $TRAVIS_BUILD_NUMBER/**/pymt*; do anaconda -t $ANACONDA_TOKEN upload $f
      --channel=$CHANNEL --user=csdms; done
    after_success:
    - rm -rf $TRAVIS_BUILD_NUMBER/*
    - rsync --delete -avR $TRAVIS_BUILD_NUMBER $DROPOFF_URL/pymt
addons:
  ssh_known_hosts: diluvium.colorado.edu
before_install:
- openssl aes-256-cbc -K $encrypted_06a730d1e26a_key -iv $encrypted_06a730d1e26a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 600 deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add deploy_rsa
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels csdms
- conda config --add channels csdms-stack
- conda config --add channels conda-forge
- conda install python=$TRAVIS_PYTHON_VERSION
script:
- conda install -q conda-build
- conda update -n root conda-build -c defaults
- conda build ./conda-recipe --no-test --old-build-string
- conda install pymt nose coverage --use-local
- nosetests --detailed-errors --exclude=examples --with-doctest --with-coverage --cover-package=pymt
  --verbosity=2 pymt
after_success:
- CONDA_PACKAGE=$(conda build --output ./conda-recipe --old-build-string)
- CONDA_ARCH=$(basename $(dirname $CONDA_PACKAGE))
- |
  if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    conda install -q coverage coveralls
    coveralls --verbose
  fi
- mkdir -p $TRAVIS_BUILD_NUMBER/$CONDA_ARCH
- mv $CONDA_PACKAGE $TRAVIS_BUILD_NUMBER/$CONDA_ARCH
- rsync -avR $TRAVIS_BUILD_NUMBER $DROPOFF_URL/pymt
