language: python
python:
    - "2.7"

os:
    - linux

install:
    - sudo apt-get install gfortran
    - bash .travis/install_esmf.sh
    - bash .travis/install_python.sh
    - export PATH="$HOME/miniconda/bin:$PATH"
    - source activate test-env
    - bash .travis/install_esmpy.sh
    - pip install coveralls

script: nosetests --with-coverage --cover-package=cmt

virtualenv:
    system_site_packages: false

after_success:
    coveralls
