env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  global:
    - secure: H0lCgCzOd++G63BDD8MMQqe5EJZwArJY4awBaEEsN/wJQD6Q3Jcbnllck3BUTi8DsMYrPxjhVdIyMFJUhokG8L/68iLUiexTIPfw2t+0uTAZ8Kxi8EuThbUyKRcfrILaLMBR5vexBb6zv7UcQrzAMDb8vTvQPJaHj5fqzJQg7wI=
    - THIS_PACKAGE=pymt
os:
- linux
- osx
sudo: false
install:
- echo "Running Travis-CI for $THIS_PACKAGE"
- echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
- if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev";
  fi
- bash .ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --add channels conda-forge
- conda info -a
- conda build -q conda-recipe -c conda-forge -c csdms
- conda install -q $THIS_PACKAGE --use-local -c conda-forge -c csdms
- pip install coveralls
script:
- nosetests --with-doctest --with-coverage --cover-package=$THIS_PACKAGE $THIS_PACKAGE
after_success:
- coveralls --verbose
- bash .ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
