{% set name = "pymt" %}
{% set version = "0.1.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy >=0.17.0
    - xarray
    - nose
    - shapely
    - netcdf4
    - pyyaml
    - esmpy
    - cfunits-python
    - numpydoc

  run:
    - python
    - setuptools
    - numpy
    - scipy >=0.17.0
    - xarray
    - nose
    - shapely
    - netcdf4
    - pyyaml
    - esmpy
    - cfunits-python
    - jinja2

test:
  requires:
    - nose
  commands:
    - nosetests --with-doctest --with-coverage --cover-package=pymt pymt

about:
  home: http://github.com/csdms/pymt
  license: MIT
  license_file: LICENSE
  summary: The CSDMS Python Modeling Tools

  description: |
    pymt is the Python interface to the CSDMS modeling tools. It provides
    utilities that run, and couple models that expose the Basic
    Model Interface.
  doc_url: http://pymt.readthedocs.org
  dev_url: http://github.com/csdms/pymt

build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}
